[program:digitalloka-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/digitalloka/artisan queue:work --sleep=1 --tries=3 --timeout=90 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/supervisor/digitalloka-worker.log
stopwaitsecs=3600
